### ISSUE TITLE
Support for folders is missing

### ISSUE THREAD

**Issue by milanaleksic** [milanaleksic/jenkins_ping#32]
There is a workaround to show at least the states by using subfolders as "server locations", but it would be better if this is done in a way that is better than following how Jenkins API works. The workaround fails to work properly the moment we have to follow UpstreamProject reference since Jenkins does not respect folder structure in this field.

Workaround is:

```toml
[[jenkins]]
location = "http://jenkins.com:8080/job/Folder"
jobs = [
    "Job"
]
```

Proper way would be:

```toml
[[jenkins]]
location = "http://jenkins.com:8080"
jobs = [
    "Folder/Job"
]
```
